export const GENRES = [
  {
    mal_id: 1,
    name: "Action",
    url: "https://myanimelist.net/manga/genre/1/Action",
    count: 10035,
  },
  {
    mal_id: 2,
    name: "Adventure",
    url: "https://myanimelist.net/manga/genre/2/Adventure",
    count: 4381,
  },
  {
    mal_id: 5,
    name: "Avant Garde",
    url: "https://myanimelist.net/manga/genre/5/Avant_Garde",
    count: 85,
  },
  {
    mal_id: 46,
    name: "Award Winning",
    url: "https://myanimelist.net/manga/genre/46/Award_Winning",
    count: 502,
  },
  {
    mal_id: 28,
    name: "Boys Love",
    url: "https://myanimelist.net/manga/genre/28/Boys_Love",
    count: 10814,
  },
  {
    mal_id: 4,
    name: "Comedy",
    url: "https://myanimelist.net/manga/genre/4/Comedy",
    count: 15466,
  },
  {
    mal_id: 8,
    name: "Drama",
    url: "https://myanimelist.net/manga/genre/8/Drama",
    count: 10426,
  },
  {
    mal_id: 10,
    name: "Fantasy",
    url: "https://myanimelist.net/manga/genre/10/Fantasy",
    count: 13127,
  },
  {
    mal_id: 26,
    name: "Girls Love",
    url: "https://myanimelist.net/manga/genre/26/Girls_Love",
    count: 1887,
  },
  {
    mal_id: 47,
    name: "Gourmet",
    url: "https://myanimelist.net/manga/genre/47/Gourmet",
    count: 547,
  },
  {
    mal_id: 14,
    name: "Horror",
    url: "https://myanimelist.net/manga/genre/14/Horror",
    count: 1869,
  },
  {
    mal_id: 7,
    name: "Mystery",
    url: "https://myanimelist.net/manga/genre/7/Mystery",
    count: 2632,
  },
  {
    mal_id: 22,
    name: "Romance",
    url: "https://myanimelist.net/manga/genre/22/Romance",
    count: 18459,
  },
  {
    mal_id: 24,
    name: "Sci-Fi",
    url: "https://myanimelist.net/manga/genre/24/Sci-Fi",
    count: 3473,
  },
  {
    mal_id: 36,
    name: "Slice of Life",
    url: "https://myanimelist.net/manga/genre/36/Slice_of_Life",
    count: 5357,
  },
  {
    mal_id: 30,
    name: "Sports",
    url: "https://myanimelist.net/manga/genre/30/Sports",
    count: 1234,
  },
  {
    mal_id: 37,
    name: "Supernatural",
    url: "https://myanimelist.net/manga/genre/37/Supernatural",
    count: 8152,
  },
  {
    mal_id: 45,
    name: "Suspense",
    url: "https://myanimelist.net/manga/genre/45/Suspense",
    count: 717,
  },
  {
    mal_id: 9,
    name: "Ecchi",
    url: "https://myanimelist.net/manga/genre/9/Ecchi",
    count: 3832,
  },
  {
    mal_id: 49,
    name: "Erotica",
    url: "https://myanimelist.net/manga/genre/49/Erotica",
    count: 10078,
  },
  {
    mal_id: 12,
    name: "Hentai",
    url: "https://myanimelist.net/manga/genre/12/Hentai",
    count: 12251,
  },
  {
    mal_id: 1,
    name: "Action",
    url: "https://myanimelist.net/manga/genre/1/Action",
    count: 10903,
  },
  {
    mal_id: 2,
    name: "Adventure",
    url: "https://myanimelist.net/manga/genre/2/Adventure",
    count: 4573,
  },
  {
    mal_id: 5,
    name: "Avant Garde",
    url: "https://myanimelist.net/manga/genre/5/Avant_Garde",
    count: 99,
  },
  {
    mal_id: 46,
    name: "Award Winning",
    url: "https://myanimelist.net/manga/genre/46/Award_Winning",
    count: 506,
  },
  {
    mal_id: 28,
    name: "Boys Love",
    url: "https://myanimelist.net/manga/genre/28/Boys_Love",
    count: 12243,
  },
  {
    mal_id: 4,
    name: "Comedy",
    url: "https://myanimelist.net/manga/genre/4/Comedy",
    count: 16323,
  },
  {
    mal_id: 8,
    name: "Drama",
    url: "https://myanimelist.net/manga/genre/8/Drama",
    count: 11341,
  },
  {
    mal_id: 10,
    name: "Fantasy",
    url: "https://myanimelist.net/manga/genre/10/Fantasy",
    count: 15219,
  },
  {
    mal_id: 26,
    name: "Girls Love",
    url: "https://myanimelist.net/manga/genre/26/Girls_Love",
    count: 2095,
  },
  {
    mal_id: 47,
    name: "Gourmet",
    url: "https://myanimelist.net/manga/genre/47/Gourmet",
    count: 664,
  },
  {
    mal_id: 14,
    name: "Horror",
    url: "https://myanimelist.net/manga/genre/14/Horror",
    count: 2019,
  },
  {
    mal_id: 7,
    name: "Mystery",
    url: "https://myanimelist.net/manga/genre/7/Mystery",
    count: 2823,
  },
  {
    mal_id: 22,
    name: "Romance",
    url: "https://myanimelist.net/manga/genre/22/Romance",
    count: 20259,
  },
  {
    mal_id: 24,
    name: "Sci-Fi",
    url: "https://myanimelist.net/manga/genre/24/Sci-Fi",
    count: 3660,
  },
  {
    mal_id: 36,
    name: "Slice of Life",
    url: "https://myanimelist.net/manga/genre/36/Slice_of_Life",
    count: 5425,
  },
  {
    mal_id: 30,
    name: "Sports",
    url: "https://myanimelist.net/manga/genre/30/Sports",
    count: 1321,
  },
  {
    mal_id: 37,
    name: "Supernatural",
    url: "https://myanimelist.net/manga/genre/37/Supernatural",
    count: 8637,
  },
  {
    mal_id: 45,
    name: "Suspense",
    url: "https://myanimelist.net/manga/genre/45/Suspense",
    count: 922,
  },
  {
    mal_id: 50,
    name: "Adult Cast",
    url: "https://myanimelist.net/manga/genre/50/Adult_Cast",
    count: 1176,
  },
  {
    mal_id: 51,
    name: "Anthropomorphic",
    url: "https://myanimelist.net/manga/genre/51/Anthropomorphic",
    count: 279,
  },
  {
    mal_id: 52,
    name: "CGDCT",
    url: "https://myanimelist.net/manga/genre/52/CGDCT",
    count: 164,
  },
  {
    mal_id: 53,
    name: "Childcare",
    url: "https://myanimelist.net/manga/genre/53/Childcare",
    count: 244,
  },
  {
    mal_id: 54,
    name: "Combat Sports",
    url: "https://myanimelist.net/manga/genre/54/Combat_Sports",
    count: 186,
  },
  {
    mal_id: 44,
    name: "Crossdressing",
    url: "https://myanimelist.net/manga/genre/44/Crossdressing",
    count: 682,
  },
  {
    mal_id: 55,
    name: "Delinquents",
    url: "https://myanimelist.net/manga/genre/55/Delinquents",
    count: 197,
  },
  {
    mal_id: 39,
    name: "Detective",
    url: "https://myanimelist.net/manga/genre/39/Detective",
    count: 444,
  },
  {
    mal_id: 56,
    name: "Educational",
    url: "https://myanimelist.net/manga/genre/56/Educational",
    count: 61,
  },
  {
    mal_id: 57,
    name: "Gag Humor",
    url: "https://myanimelist.net/manga/genre/57/Gag_Humor",
    count: 318,
  },
  {
    mal_id: 58,
    name: "Gore",
    url: "https://myanimelist.net/manga/genre/58/Gore",
    count: 271,
  },
  {
    mal_id: 35,
    name: "Harem",
    url: "https://myanimelist.net/manga/genre/35/Harem",
    count: 2443,
  },
  {
    mal_id: 59,
    name: "High Stakes Game",
    url: "https://myanimelist.net/manga/genre/59/High_Stakes_Game",
    count: 95,
  },
  {
    mal_id: 13,
    name: "Historical",
    url: "https://myanimelist.net/manga/genre/13/Historical",
    count: 2691,
  },
  {
    mal_id: 60,
    name: "Idols (Female)",
    url: "https://myanimelist.net/manga/genre/60/Idols_Female",
    count: 80,
  },
  {
    mal_id: 61,
    name: "Idols (Male)",
    url: "https://myanimelist.net/manga/genre/61/Idols_Male",
    count: 81,
  },
  {
    mal_id: 62,
    name: "Isekai",
    url: "https://myanimelist.net/manga/genre/62/Isekai",
    count: 1582,
  },
  {
    mal_id: 63,
    name: "Iyashikei",
    url: "https://myanimelist.net/manga/genre/63/Iyashikei",
    count: 155,
  },
  {
    mal_id: 64,
    name: "Love Polygon",
    url: "https://myanimelist.net/manga/genre/64/Love_Polygon",
    count: 355,
  },
  {
    mal_id: 65,
    name: "Magical Sex Shift",
    url: "https://myanimelist.net/manga/genre/65/Magical_Sex_Shift",
    count: 274,
  },
  {
    mal_id: 66,
    name: "Mahou Shoujo",
    url: "https://myanimelist.net/manga/genre/66/Mahou_Shoujo",
    count: 176,
  },
  {
    mal_id: 17,
    name: "Martial Arts",
    url: "https://myanimelist.net/manga/genre/17/Martial_Arts",
    count: 779,
  },
  {
    mal_id: 18,
    name: "Mecha",
    url: "https://myanimelist.net/manga/genre/18/Mecha",
    count: 741,
  },
  {
    mal_id: 67,
    name: "Medical",
    url: "https://myanimelist.net/manga/genre/67/Medical",
    count: 183,
  },
  {
    mal_id: 68,
    name: "Memoir",
    url: "https://myanimelist.net/manga/genre/68/Memoir",
    count: 219,
  },
  {
    mal_id: 38,
    name: "Military",
    url: "https://myanimelist.net/manga/genre/38/Military",
    count: 770,
  },
  {
    mal_id: 19,
    name: "Music",
    url: "https://myanimelist.net/manga/genre/19/Music",
    count: 589,
  },
  {
    mal_id: 6,
    name: "Mythology",
    url: "https://myanimelist.net/manga/genre/6/Mythology",
    count: 895,
  },
  {
    mal_id: 69,
    name: "Organized Crime",
    url: "https://myanimelist.net/manga/genre/69/Organized_Crime",
    count: 217,
  },
  {
    mal_id: 70,
    name: "Otaku Culture",
    url: "https://myanimelist.net/manga/genre/70/Otaku_Culture",
    count: 168,
  },
  {
    mal_id: 20,
    name: "Parody",
    url: "https://myanimelist.net/manga/genre/20/Parody",
    count: 372,
  },
  {
    mal_id: 71,
    name: "Performing Arts",
    url: "https://myanimelist.net/manga/genre/71/Performing_Arts",
    count: 138,
  },
  {
    mal_id: 72,
    name: "Pets",
    url: "https://myanimelist.net/manga/genre/72/Pets",
    count: 182,
  },
  {
    mal_id: 40,
    name: "Psychological",
    url: "https://myanimelist.net/manga/genre/40/Psychological",
    count: 1696,
  },
  {
    mal_id: 3,
    name: "Racing",
    url: "https://myanimelist.net/manga/genre/3/Racing",
    count: 82,
  },
  {
    mal_id: 73,
    name: "Reincarnation",
    url: "https://myanimelist.net/manga/genre/73/Reincarnation",
    count: 1085,
  },
  {
    mal_id: 74,
    name: "Reverse Harem",
    url: "https://myanimelist.net/manga/genre/74/Reverse_Harem",
    count: 182,
  },
  {
    mal_id: 75,
    name: "Love Status Quo",
    url: "https://myanimelist.net/manga/genre/75/Love_Status_Quo",
    count: 359,
  },
  {
    mal_id: 21,
    name: "Samurai",
    url: "https://myanimelist.net/manga/genre/21/Samurai",
    count: 297,
  },
  {
    mal_id: 23,
    name: "School",
    url: "https://myanimelist.net/manga/genre/23/School",
    count: 11968,
  },
  {
    mal_id: 76,
    name: "Showbiz",
    url: "https://myanimelist.net/manga/genre/76/Showbiz",
    count: 192,
  },
  {
    mal_id: 29,
    name: "Space",
    url: "https://myanimelist.net/manga/genre/29/Space",
    count: 275,
  },
  {
    mal_id: 11,
    name: "Strategy Game",
    url: "https://myanimelist.net/manga/genre/11/Strategy_Game",
    count: 307,
  },
  {
    mal_id: 31,
    name: "Super Power",
    url: "https://myanimelist.net/manga/genre/31/Super_Power",
    count: 655,
  },
  {
    mal_id: 77,
    name: "Survival",
    url: "https://myanimelist.net/manga/genre/77/Survival",
    count: 190,
  },
  {
    mal_id: 78,
    name: "Team Sports",
    url: "https://myanimelist.net/manga/genre/78/Team_Sports",
    count: 461,
  },
  {
    mal_id: 79,
    name: "Time Travel",
    url: "https://myanimelist.net/manga/genre/79/Time_Travel",
    count: 703,
  },
  {
    mal_id: 32,
    name: "Vampire",
    url: "https://myanimelist.net/manga/genre/32/Vampire",
    count: 579,
  },
  {
    mal_id: 80,
    name: "Video Game",
    url: "https://myanimelist.net/manga/genre/80/Video_Game",
    count: 351,
  },
  {
    mal_id: 81,
    name: "Villainess",
    url: "https://myanimelist.net/manga/genre/81/Villainess",
    count: 379,
  },
  {
    mal_id: 82,
    name: "Visual Arts",
    url: "https://myanimelist.net/manga/genre/82/Visual_Arts",
    count: 120,
  },
  {
    mal_id: 48,
    name: "Workplace",
    url: "https://myanimelist.net/manga/genre/48/Workplace",
    count: 623,
  },
  {
    mal_id: 83,
    name: "Urban Fantasy",
    url: "https://myanimelist.net/manga/genre/83/Urban_Fantasy",
    count: 92,
  },
  {
    mal_id: 9,
    name: "Ecchi",
    url: "https://myanimelist.net/manga/genre/9/Ecchi",
    count: 4005,
  },
  {
    mal_id: 49,
    name: "Erotica",
    url: "https://myanimelist.net/manga/genre/49/Erotica",
    count: 11515,
  },
  {
    mal_id: 12,
    name: "Hentai",
    url: "https://myanimelist.net/manga/genre/12/Hentai",
    count: 13863,
  },
  {
    mal_id: 42,
    name: "Josei",
    url: "https://myanimelist.net/manga/genre/42/Josei",
    count: 4442,
  },
  {
    mal_id: 15,
    name: "Kids",
    url: "https://myanimelist.net/manga/genre/15/Kids",
    count: 293,
  },
  {
    mal_id: 41,
    name: "Seinen",
    url: "https://myanimelist.net/manga/genre/41/Seinen",
    count: 8539,
  },
  {
    mal_id: 25,
    name: "Shoujo",
    url: "https://myanimelist.net/manga/genre/25/Shoujo",
    count: 8566,
  },
  {
    mal_id: 27,
    name: "Shounen",
    url: "https://myanimelist.net/manga/genre/27/Shounen",
    count: 7100,
  },
  {
    mal_id: 50,
    name: "Adult Cast",
    url: "https://myanimelist.net/manga/genre/50/Adult_Cast",
    count: 1727,
  },
  {
    mal_id: 51,
    name: "Anthropomorphic",
    url: "https://myanimelist.net/manga/genre/51/Anthropomorphic",
    count: 367,
  },
  {
    mal_id: 52,
    name: "CGDCT",
    url: "https://myanimelist.net/manga/genre/52/CGDCT",
    count: 175,
  },
  {
    mal_id: 53,
    name: "Childcare",
    url: "https://myanimelist.net/manga/genre/53/Childcare",
    count: 297,
  },
  {
    mal_id: 54,
    name: "Combat Sports",
    url: "https://myanimelist.net/manga/genre/54/Combat_Sports",
    count: 207,
  },
  {
    mal_id: 44,
    name: "Crossdressing",
    url: "https://myanimelist.net/manga/genre/44/Crossdressing",
    count: 750,
  },
  {
    mal_id: 55,
    name: "Delinquents",
    url: "https://myanimelist.net/manga/genre/55/Delinquents",
    count: 222,
  },
  {
    mal_id: 39,
    name: "Detective",
    url: "https://myanimelist.net/manga/genre/39/Detective",
    count: 501,
  },
  {
    mal_id: 56,
    name: "Educational",
    url: "https://myanimelist.net/manga/genre/56/Educational",
    count: 73,
  },
  {
    mal_id: 57,
    name: "Gag Humor",
    url: "https://myanimelist.net/manga/genre/57/Gag_Humor",
    count: 401,
  },
  {
    mal_id: 58,
    name: "Gore",
    url: "https://myanimelist.net/manga/genre/58/Gore",
    count: 365,
  },
  {
    mal_id: 35,
    name: "Harem",
    url: "https://myanimelist.net/manga/genre/35/Harem",
    count: 2603,
  },
  {
    mal_id: 59,
    name: "High Stakes Game",
    url: "https://myanimelist.net/manga/genre/59/High_Stakes_Game",
    count: 114,
  },
  {
    mal_id: 13,
    name: "Historical",
    url: "https://myanimelist.net/manga/genre/13/Historical",
    count: 2910,
  },
  {
    mal_id: 60,
    name: "Idols (Female)",
    url: "https://myanimelist.net/manga/genre/60/Idols_Female",
    count: 101,
  },
  {
    mal_id: 61,
    name: "Idols (Male)",
    url: "https://myanimelist.net/manga/genre/61/Idols_Male",
    count: 114,
  },
  {
    mal_id: 62,
    name: "Isekai",
    url: "https://myanimelist.net/manga/genre/62/Isekai",
    count: 2179,
  },
  {
    mal_id: 63,
    name: "Iyashikei",
    url: "https://myanimelist.net/manga/genre/63/Iyashikei",
    count: 162,
  },
  {
    mal_id: 64,
    name: "Love Polygon",
    url: "https://myanimelist.net/manga/genre/64/Love_Polygon",
    count: 449,
  },
  {
    mal_id: 75,
    name: "Love Status Quo",
    url: "https://myanimelist.net/manga/genre/75/Love_Status_Quo",
    count: 277,
  },
  {
    mal_id: 65,
    name: "Magical Sex Shift",
    url: "https://myanimelist.net/manga/genre/65/Magical_Sex_Shift",
    count: 307,
  },
  {
    mal_id: 66,
    name: "Mahou Shoujo",
    url: "https://myanimelist.net/manga/genre/66/Mahou_Shoujo",
    count: 194,
  },
  {
    mal_id: 17,
    name: "Martial Arts",
    url: "https://myanimelist.net/manga/genre/17/Martial_Arts",
    count: 871,
  },
  {
    mal_id: 18,
    name: "Mecha",
    url: "https://myanimelist.net/manga/genre/18/Mecha",
    count: 770,
  },
  {
    mal_id: 67,
    name: "Medical",
    url: "https://myanimelist.net/manga/genre/67/Medical",
    count: 212,
  },
  {
    mal_id: 68,
    name: "Memoir",
    url: "https://myanimelist.net/manga/genre/68/Memoir",
    count: 252,
  },
  {
    mal_id: 38,
    name: "Military",
    url: "https://myanimelist.net/manga/genre/38/Military",
    count: 805,
  },
  {
    mal_id: 19,
    name: "Music",
    url: "https://myanimelist.net/manga/genre/19/Music",
    count: 657,
  },
  {
    mal_id: 6,
    name: "Mythology",
    url: "https://myanimelist.net/manga/genre/6/Mythology",
    count: 975,
  },
  {
    mal_id: 69,
    name: "Organized Crime",
    url: "https://myanimelist.net/manga/genre/69/Organized_Crime",
    count: 289,
  },
  {
    mal_id: 70,
    name: "Otaku Culture",
    url: "https://myanimelist.net/manga/genre/70/Otaku_Culture",
    count: 230,
  },
  {
    mal_id: 20,
    name: "Parody",
    url: "https://myanimelist.net/manga/genre/20/Parody",
    count: 400,
  },
  {
    mal_id: 71,
    name: "Performing Arts",
    url: "https://myanimelist.net/manga/genre/71/Performing_Arts",
    count: 154,
  },
  {
    mal_id: 72,
    name: "Pets",
    url: "https://myanimelist.net/manga/genre/72/Pets",
    count: 238,
  },
  {
    mal_id: 40,
    name: "Psychological",
    url: "https://myanimelist.net/manga/genre/40/Psychological",
    count: 1825,
  },
  {
    mal_id: 3,
    name: "Racing",
    url: "https://myanimelist.net/manga/genre/3/Racing",
    count: 92,
  },
  {
    mal_id: 73,
    name: "Reincarnation",
    url: "https://myanimelist.net/manga/genre/73/Reincarnation",
    count: 1547,
  },
  {
    mal_id: 74,
    name: "Reverse Harem",
    url: "https://myanimelist.net/manga/genre/74/Reverse_Harem",
    count: 228,
  },
  {
    mal_id: 21,
    name: "Samurai",
    url: "https://myanimelist.net/manga/genre/21/Samurai",
    count: 315,
  },
  {
    mal_id: 23,
    name: "School",
    url: "https://myanimelist.net/manga/genre/23/School",
    count: 12737,
  },
  {
    mal_id: 76,
    name: "Showbiz",
    url: "https://myanimelist.net/manga/genre/76/Showbiz",
    count: 251,
  },
  {
    mal_id: 29,
    name: "Space",
    url: "https://myanimelist.net/manga/genre/29/Space",
    count: 305,
  },
  {
    mal_id: 11,
    name: "Strategy Game",
    url: "https://myanimelist.net/manga/genre/11/Strategy_Game",
    count: 321,
  },
  {
    mal_id: 31,
    name: "Super Power",
    url: "https://myanimelist.net/manga/genre/31/Super_Power",
    count: 702,
  },
  {
    mal_id: 77,
    name: "Survival",
    url: "https://myanimelist.net/manga/genre/77/Survival",
    count: 231,
  },
  {
    mal_id: 78,
    name: "Team Sports",
    url: "https://myanimelist.net/manga/genre/78/Team_Sports",
    count: 501,
  },
  {
    mal_id: 79,
    name: "Time Travel",
    url: "https://myanimelist.net/manga/genre/79/Time_Travel",
    count: 952,
  },
  {
    mal_id: 83,
    name: "Urban Fantasy",
    url: "https://myanimelist.net/manga/genre/83/Urban_Fantasy",
    count: 395,
  },
  {
    mal_id: 32,
    name: "Vampire",
    url: "https://myanimelist.net/manga/genre/32/Vampire",
    count: 640,
  },
  {
    mal_id: 80,
    name: "Video Game",
    url: "https://myanimelist.net/manga/genre/80/Video_Game",
    count: 404,
  },
  {
    mal_id: 81,
    name: "Villainess",
    url: "https://myanimelist.net/manga/genre/81/Villainess",
    count: 483,
  },
  {
    mal_id: 82,
    name: "Visual Arts",
    url: "https://myanimelist.net/manga/genre/82/Visual_Arts",
    count: 143,
  },
  {
    mal_id: 48,
    name: "Workplace",
    url: "https://myanimelist.net/manga/genre/48/Workplace",
    count: 872,
  },
];

export const scores = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"];

export const RATINGS = [
  { value: "g", label: "G" },
  { value: "pg", label: "PG" },
  { value: "pg13", label: "PG-13" },
  { value: "r17", label: "R-17" },
  { value: "r", label: "R" },
  { value: "rx", label: "RX" },
] as const;

export const STATUS = [
  {
    value: "airing",
    label: "Airing",
  },
  {
    value: "complete",
    label: "Complete",
  },
  {
    value: "upcoming",
    label: "Upcoming",
  },
];

export const SORT = [
  {
    value: "asc",
    label: "Ascending",
  },
  {
    value: "desc",
    label: "Descending",
  },
];

export const TYPES = [
  { value: "tv", label: "TV" },
  { value: "movie", label: "Movie" },
  { value: "ova", label: "OVA" },
  { value: "special", label: "Special" },
  { value: "ona", label: "ONA" },
  { value: "music", label: "Music" },
  { value: "cm", label: "CM" },
  { value: "pv", label: "PV" },
  { value: "tv_special", label: "TV Special" },
];

export const OrderBy = [
  { value: "mal_id", label: "MAL ID" },
  { value: "title", label: "Title" },
  { value: "start_date", label: "Start date" },
  { value: "end_date", label: "End date" },
  { value: "episodes", label: "Episodes" },
  { value: "score", label: "Score" },
  { value: "scored_by", label: "Scored by" },
  { value: "rank", label: "Rank" },
  { value: "popularity", label: "Popularity" },
  { value: "members", label: "Members" },
  { value: "favorites", label: "Favorites" },
];
